---
displaymanagers:
  - sddm
basicSetup: false
sysconfigSetup: false
defaultDesktopEnvironment:
    executable: "startplasma-wayland"
    desktopFile: "plasma"
sddm:
  configuration_file: "/etc/sddm.conf"
