---
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    512MiB
    minimumSize:        300MiB
    label:              "EFI"
userSwapChoices:
    - none
    - small
    - suspend
    - file
luksGeneration: luks2
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType:  "btrfs"
availableFileSystemTypes:  ["btrfs", "ext4", "xfs"]
essentialMounts: [ "live-*", "control", "ventoy" ]
lvm:
    enable: true
