---
units:
  - name: NetworkManager.service
    action: enable
    mandatory: false
  - name: bluetooth.service
    action: enable
    mandatory: false
  - name: sddm.service
    action: enable
    mandatory: true
  - name: graphical.target
    action: set-default
    mandatory: false
  - name: fstrim.timer
    action: enable
    mandatory: false
