---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - name: wheel
      must_exist: false
      system: true
    - video
    - render
    - input
    - audio
    - lp
    - network
    - storage
sudoersGroup:    wheel
sudoersConfigureWithGroup: true
autologinGroup:  autologin
setRootPassword: false
doReusePassword: true
displayAutologin: true
doAutologin:     false
passwordRequirements:
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
user:
  shell: /bin/bash
  forbidden_names: [ root, firelamp ]
  home_permissions: "o700"
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "firelamp-${cpu}"
  forbidden_names: [ localhost ]
