title    Firelamp OS (%ARCH%, UEFI) console only
sort-key 04
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% systemd.unit=multi-user.target %KERNEL_PARAMS%
